# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out CDK Repository
      - uses: actions/checkout@v2
        with: 
          repository: sagardsaxena/StocksCDK
          path: ./StocksCDK

      # Checks-out ReactApp Repository
      - uses: actions/checkout@v2
        with: 
          repository: sagardsaxena/StocksReactApp
          path: ./StocksReactApp
          

      # Runs a single command using the runners shell
      - name: Get current directory
        run: pwd

      # Runs a set of commands using the runners shell
      - name: Clone website directory
        run: |
          pwd
